#ifndef __I2C_MNEMONICS_H__
#define __I2C_MNEMONICS_H__


#define WRITE 0
#define READ 1
#define ENABLE_ACK 1
#define DISABLE_ACK 0

#define MASTER_START_TRANSMITTED 0x08
#define MASTER_REPEATED_START_TRANSMITTED 0x10
#define MASTER_SLAW_ACK_REC 0x18
#define MASTER_SLAW_NACK_REC 0x20
#define MASTER_DATA_TRANSMITTED_ACK_REC 0x28
#define MASTER_DATA_TRANSMITTED_NACK_REC 0x30
#define MASTER_SLAR_ACK_REC 0x40
#define MASTER_SLAR_NACK_REC 0x48
#define MASTER_DATA_RECEIVED_ACK_RET 0x50
#define MASTER_DATA_RECEIVED_NACK_RET 0x58
#define SLAVE_SLAW_RECEIVED_ACK_RET 0x60
#define SLAVE_DATA_RECEIVED_ACK_RET 0x80
#define SLAVE_DATA_RECEIVED_NACK_RET 0x88
#define SLAVE_STOP_REPSTART_RECEIVED 0xA0
#define SLAVE_SLAR_RECEIVED_ACK_RET 0xA8
#define SLAVE_DATA_TRANSMITTED_ACK_REC 0xB8
#define SLAVE_DATA_TRANSMITTED_NACK_REC 0xC0
#define SLAVE_LAST_DATA_TRANSMITTED_ACK_REC 0xC8



#endif