#ifndef __MPU6050_MNEMONICS_H__
#define __MPU6050_MNEMONICS_H__


#define MPU_ADDRESS 104 
#define MPU_RA_CONFIG 0x1A
#define MPU_RA_GYRO_CONFIG 0x1B
#define MPU_RA_ACCEL_CONFIG 0x1C
#define MPU_RA_FIFO_EN 0x23
#define MPU_RA_INT_PIN_CONFIG 0x37
#define MPU_RA_INT_ENABLE 0x38
#define MPU_RA_INT_STATUS 0x3A
#define MPU_RA_ACCEL_XOUT_H 0x3B
#define MPU_RA_ACCEL_XOUT_L 0x3C
#define MPU_RA_ACCEL_YOUT_H 0x3D
#define MPU_RA_ACCEL_YOUT_L 0x3E
#define MPU_RA_ACCEL_ZOUT_H 0x3F
#define MPU_RA_ACCEL_ZOUT_L 0x40
#define MPU_RA_TEMP_OUT_H 0x41
#define MPU_RA_TEMP_OUT_L 0x42
#define MPU_RA_GYRO_XOUT_H 0x43
#define MPU_RA_GYRO_XOUT_L 0x44
#define MPU_RA_GYRO_YOUT_H 0x45
#define MPU_RA_GYRO_YOUT_L 0x46
#define MPU_RA_GYRO_ZOUT_H 0x47
#define MPU_RA_GYRO_ZOUT_L 0x48
#define MPU_RA_SIGNAL_PATH_RESET 0x68
#define MPU_RA_USER_CTRL 0x6A
#define MPU_RA_PWR_MGMT_1 0x6B
#define MPU_RA_PWR_MGMT_2 0x6C
#define MPU_RA_FIFO_COUNTH 0x72
#define MPU_RA_FIFO_COUNTL 0x73
#define MPU_RA_FIFO_DATA8 0x74

#define MPU_BIT_TEMP_FIFO_EN 128
#define MPU_BIT_XG_FIFO_EN 64
#define MPU_BIT_YG_FIFO_EN 32
#define MPU_BIT_ZG_FIFO_EN 16
#define MPU_BIT_ACCEL_FIFO_EN 8
#define MPU_BIT_SLV2_FIFO_EN 4
#define MPU_BIT_SLV1_FIFO_EN 2
#define MPU_BIT_SLV0_FIFO_EN 1
#define MPU_BIT_INT_CNFG_INT_LEVEL_ACT_HIGH 128
#define MPU_BIT_INT_CNFG_LATCHINT_EN_50us 32
#define MPU_BIT_INT_CNFG_INT_RD_CLEAR_READING_STATUS 16
#define MPU_BIT_INT_EN_FIFO_OVF_EN 16
#define MPU_BIT_INT_EN_MST_EN 8
#define MPU_BIT_INT_EN_DATA_RDY_EN 1
#define MPU_BIT_INT_STATUS_FIFO_OVF 16
#define MPU_BIT_INT_STATUS_DATA_RDY 1
#define MPU_BIT_SIGNAL_PATH_RESET_GYRO 4
#define MPU_BIT_SIGNAL_PATH_RESET_ACCEL 2
#define MPU_BIT_SIGNAL_PATH_RESET_TEMP 1
#define MPU_BIT_USER_CTRL_FIFO_EN 64
#define MPU_BIT_USER_CTRL_FIFO_RESET 4
#define MPU_BIT_USER_CTRL_SIG_COND_RESET 1
#define MPU_BIT_PWR_MGMT1_DEVICE_RESET 128
#define MPU_BIT_PWR_MGMT1_SLEEP 64
#define MPU_BIT_PWR_MGMT1_CYCLE 32

#endif